### ISSUE TITLE
Does MMM-Keypress recognize mouse wheel movement?

### ISSUE THREAD

**Issue by Unclearogre** [ItsMeBrille/MMM-Keypress#1]
I am trying to get a MagicMirror set up and am planning on using your MMM-Keypress module along with MMM-Pages to switch between a family dashboard and a slideshow of famous paintings.  I would love to be able to use a mouse wheelup and wheeldown to trigger the previous and next painting but can't figure out what to put for the key code.  Does your module support this?

Thanks!

**Comment by ItsMeBrille** [comment]
It does not currently, but I can take a look and ill sse what I can do. Also, a star would be appreciated, so i can more easily see what modules I should develop further 😎

**Comment by Unclearogre** [comment]
No worries...  My case is that I'm using MMM-BackgroundSlideshow and thought it would be cool to use the mousewheel to scroll through the images.  It's certainly not necessary or anything.  

I'm new to github so I didn't know about the star thing (I assume it's like the like button on YouTube?) but I've starred the project now.  Thanks!
